### ISSUE TITLE
Server Requirements for Iteration 1

### ISSUE THREAD

**Issue by MitchellHamm** [colindignazio/comp4350#3]
For iteration 1 we are going to need to setup a few AWS servers. Ideally we would have 1 server for the database, 1 server for the CodeIgniter API and 1 server for the website itself. AWS offers 12 months of free web service.

**Comment by MitchellHamm** [comment]
I will look into if we can get 3 servers for free under one account, or if we'll need to create 3 accounts to get free servers.

**Comment by MitchellHamm** [comment]
We can use virtual hosts to fake the appearance of multiple servers meaning we will only need 1 server for API and Web and Amazons RDS will handle our database.

**Comment by MitchellHamm** [comment]
I have set up our API on AWS. The codeIgniter root has been installed along with LAMP stack. I have .pem keys for accessing the server root via ssh, I will find a secure way to give these out as anyone who has one will have root access to our servers.

**Comment by DPCode** [comment]
Woah! Nice work! The test works for me!

**Comment by DPCode** [comment]
Can any of that go in the repo?

**Comment by MitchellHamm** [comment]
Yeah I just need to fix a few things up so its a little more ready but I'll get it in the repo and show you all how you can host it locally to develop the API

**Comment by DPCode** [comment]
You may be aware, but the URL is returning a PHP error.

![error](https://cloud.githubusercontent.com/assets/7504938/12471741/2c1413ee-bfc6-11e5-9242-86af08061a55.png)

**Comment by MitchellHamm** [comment]
Please be aware the API is non functional right now. I had to clean out the existing files and drop in an entire set of new ones due to some permissions. You're problem was probably because the API was in the process of being deleted.

**Comment by MitchellHamm** [comment]
![screen shot 2016-01-20 at 11 06 57 pm](https://cloud.githubusercontent.com/assets/13455818/12472129/8e22f466-bfca-11e5-8e67-fab1796e073f.png)
Heres a sample of the POST done with Postman, the parameter must be named message for the function to recognize it properly.

**Comment by MitchellHamm** [comment]
Back-end servers are up and running! Our API server is now looking at an AWS RDS database, I populated a test table with one test result. If you send a POST request to: http://54.200.14.217/?/testDatabase you'll retrieve my test column from the database.

At some point we should meet so I can distribute all the private keys and login information for the ubuntu API server and the RDS server so that everyone can get into them.

**Comment by DPCode** [comment]
Does the post require any additional setup?
I'm getting a 
"{
  "status": 403,
  "msg": "Forbidden",
  "details": "You do not have access to the requested resource."
}"

**Comment by MitchellHamm** [comment]
Seems like the browser isn't a big fan of that for some reason. My browser is also returning the same.
I tested mine via Postman which is giving expected results, maybe give that a try instead. I'm thinking it's redirecting to the html page for that route for some reason which is just access forbidden on every page. Let me know if you have any troubles with Postman.

**Comment by DPCode** [comment]
Yeah. That was through postman:
![postman](https://cloud.githubusercontent.com/assets/7504938/12472662/442e86b2-bfd0-11e5-8379-02d57daf6489.png)

Should it be a GET instead of a POST? It didn't make a difference for me.

**Comment by MitchellHamm** [comment]
Going to be honest here, I goofed big time and forgot to include /user infront of the testDatabase call when I put it in the comment. I fixed the link so it should work now, sorry about the confusion.

**Comment by DPCode** [comment]
Got it working now with 'user' added. 
http://54.200.14.217/?/user/testDatabase

Huge Props! Thanks again for getting this working
